---
kind: pipeline
name: prepare
trigger:
  branch:
  - master
  event:
  - push
clone:
  disable: true

steps:
- name: register-qemu
  image: multiarch/qemu-user-static:register
  command: [ "--reset" ]
  privileged: true

---
kind: pipeline
name: red-discordbot-noaudio
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
  volumes:
    - name: cache
      path: /cache

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags: noaudio-arm64v8
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm64v8
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags: noaudio-arm32v7
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm32v7
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags: noaudio-amd64
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-amd64
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest-noaudio
  image: plugins/manifest:1
  environment:
    DRONE_TAG: noaudio
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: red-discordbot-audio
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
  volumes:
    - name: cache
      path: /cache

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags:
      - audio-arm64v8
      - latest-arm64v8
    build_args:
      - ARCH_IMG=phasecorex/red-discordbot:noaudio-arm64v8
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags:
      - audio-arm32v7
      - latest-arm32v7
    build_args:
      - ARCH_IMG=phasecorex/red-discordbot:noaudio-arm32v7
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    use_cache: true
    repo: phasecorex/red-discordbot
    tags:
      - audio-amd64
      - latest-amd64
    build_args:
      - ARCH_IMG=phasecorex/red-discordbot:noaudio-amd64
    build_args_from_env:
      - DRONE_COMMIT_SHA
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest-audio
  image: plugins/manifest:1
  environment:
    DRONE_TAG: audio
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-latest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - red-discordbot-noaudio

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - red-discordbot-noaudio
  - red-discordbot-audio

