---
kind: pipeline
name: red-discordbot-noaudio
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/red-discordbot:noaudio-arm64v8
    repo: phasecorex/red-discordbot
    tags: noaudio-arm64v8
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm64v8
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/red-discordbot:noaudio-arm32v7
    repo: phasecorex/red-discordbot
    tags: noaudio-arm32v7
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm32v7
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/red-discordbot:noaudio-amd64
    repo: phasecorex/red-discordbot
    tags: noaudio-amd64
    dockerfile: Dockerfile.noaudio
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-amd64
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-push-manifest-noaudio
  image: plugins/manifest:1
  environment:
    DRONE_TAG: noaudio
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

depends_on:
  - prepare

---
kind: pipeline
name: red-discordbot-audio
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:noaudio-arm64v8
      - phasecorex/red-discordbot:audio-arm64v8
    repo: phasecorex/red-discordbot
    tags:
      - audio-arm64v8
      - latest-arm64v8
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm64v8
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:noaudio-arm32v7
      - phasecorex/red-discordbot:audio-arm32v7
    repo: phasecorex/red-discordbot
    tags:
      - audio-arm32v7
      - latest-arm32v7
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm32v7
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:noaudio-amd64
      - phasecorex/red-discordbot:audio-amd64
    repo: phasecorex/red-discordbot
    tags:
      - audio-amd64
      - latest-amd64
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-amd64
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-push-manifest-audio
  image: plugins/manifest:1
  environment:
    DRONE_TAG: audio
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-latest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

depends_on:
  - red-discordbot-noaudio

---
kind: pipeline
name: red-discordbot-full
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:audio-arm64v8
      - phasecorex/red-discordbot:full-arm64v8
    repo: phasecorex/red-discordbot
    tags: full-arm64v8
    dockerfile: Dockerfile.full
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm64v8
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:audio-arm32v7
      - phasecorex/red-discordbot:full-arm32v7
    repo: phasecorex/red-discordbot
    tags: full-arm32v7
    dockerfile: Dockerfile.full
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-arm32v7
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from:
      - phasecorex/red-discordbot:audio-amd64
      - phasecorex/red-discordbot:full-amd64
    repo: phasecorex/red-discordbot
    tags: full-amd64
    dockerfile: Dockerfile.full
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-slim-amd64
    build_args_from_env:
      - DRONE_COMMIT_SHA

- name: docker-push-manifest-full
  image: plugins/manifest:1
  environment:
    DRONE_TAG: full
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

depends_on:
  - red-discordbot-audio

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - red-discordbot-noaudio
  - red-discordbot-audio
  - red-discordbot-full

