---
kind: pipeline
name: prepare
trigger:
  branch:
  - master
  event:
  - push
clone:
  disable: true

steps:
- name: register-qemu
  image: multiarch/qemu-user-static:register
  command: [ "--reset" ]
  privileged: true

---
kind: pipeline
name: red-discordbot-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: slim-arm64v8
    dockerfile: Dockerfile.slim
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: slim-arm32v7
    dockerfile: Dockerfile.slim
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm32v7

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: slim-arm32v6
    dockerfile: Dockerfile.slim
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: slim-amd64
    dockerfile: Dockerfile.slim
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-amd64

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

depends_on:
  - prepare

---
kind: pipeline
name: red-discordbot-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: latest-arm64v8
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: latest-arm32v7
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm32v7

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: latest-arm32v6
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/red-discordbot
    tags: latest-amd64
    build_args:
      - ARCH_IMG=phasecorex/user-python:3.7-alpine-amd64

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

depends_on:
  - red-discordbot-slim

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - red-discordbot-slim
  - red-discordbot-latest

