name: build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  repository_dispatch:
    types: [upstream_image_update]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      -
        name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=phasecorex/red-discordbot
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push noaudio
        uses: docker/build-push-action@v2
        with:
          target: noaudio
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.docker_image }}:noaudio,ghcr.io/${{ steps.prep.outputs.docker_image }}:noaudio
          build-args: |
            PCX_DISCORDBOT_COMMIT=${{ github.sha }}
          cache-from: |
            ${{ steps.prep.outputs.docker_image }}:noaudio
          labels: |
            maintainer=Ryan Foster <phasecorex@gmail.com>
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=noaudio
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Build and push audio
        uses: docker/build-push-action@v2
        with:
          target: audio
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.docker_image }}:audio,ghcr.io/${{ steps.prep.outputs.docker_image }}:audio,${{ steps.prep.outputs.docker_image }}:latest,ghcr.io/${{ steps.prep.outputs.docker_image }}:latest
          build-args: |
            PCX_DISCORDBOT_COMMIT=${{ github.sha }}
          cache-from: |
            ${{ steps.prep.outputs.docker_image }}:noaudio
            ${{ steps.prep.outputs.docker_image }}:audio
          labels: |
            maintainer=Ryan Foster <phasecorex@gmail.com>
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=audio
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Build and push full
        uses: docker/build-push-action@v2
        with:
          target: full
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.docker_image }}:full,ghcr.io/${{ steps.prep.outputs.docker_image }}:full
          build-args: |
            PCX_DISCORDBOT_COMMIT=${{ github.sha }}
          cache-from: |
            ${{ steps.prep.outputs.docker_image }}:audio
            ${{ steps.prep.outputs.docker_image }}:full
          labels: |
            maintainer=Ryan Foster <phasecorex@gmail.com>
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=full
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ steps.prep.outputs.docker_image }}:noaudio
          docker buildx imagetools inspect ${{ steps.prep.outputs.docker_image }}:audio
          docker buildx imagetools inspect ${{ steps.prep.outputs.docker_image }}:full
      -
        name: Check pull
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ steps.prep.outputs.docker_image }}:noaudio
          docker pull ${{ steps.prep.outputs.docker_image }}:audio
          docker pull ${{ steps.prep.outputs.docker_image }}:full
          docker pull ghcr.io/${{ steps.prep.outputs.docker_image }}:noaudio
          docker pull ghcr.io/${{ steps.prep.outputs.docker_image }}:audio
          docker pull ghcr.io/${{ steps.prep.outputs.docker_image }}:full
